services:
  - type: web
    name: gpt-jobs-api
    runtime: docker
    plan: free
    region: singapore
    dockerContext: ./backend
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: NODE_ENV
        value: production
      - key: FIREBASE_PROJECT_ID
        value: gpt-jobs-dev
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /dev/null
